export const carparkList = [
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "BASEMENT CAR PARK",
        "x_coord": "1.376082",
        "y_coord": "103.774277",
        "free_parking": "NO",
        "gantry_height": "1.80",
        "car_park_basement": "Y",
        "night_parking": "YES",
        "address": "BLK 270/271 ALBERT CENTRE BASEMENT CAR PARK",
        "car_park_decks": "1",
        "_id": 1,
        "car_park_no": "ACB",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "x_coord": "1.3212167",
        "y_coord": "103.8849432",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.10",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 98A ALJUNIED CRESCENT",
        "car_park_decks": "5",
        "_id": 2,
        "car_park_no": "ACM",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "x_coord": "1.3289149",
        "y_coord": "103.8430038",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 101 JALAN DUSUN",
        "car_park_decks": "0",
        "_id": 3,
        "car_park_no": "AH1",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "7AM-7PM",
        "car_park_type": "SURFACE CAR PARK",
        "x_coord": "1.3697648",
        "y_coord": "103.8345326",
        "free_parking": "NO",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "BLOCK 253 ANG MO KIO STREET 21",
        "car_park_decks": "0",
        "_id": 4,
        "car_park_no": "AK19",
        "type_of_parking_system": "COUPON PARKING"
    },
    {
        "short_term_parking": "NO",
        "car_park_type": "SURFACE CAR PARK",
        "x_coord": "1.3659029",
        "y_coord": "103.8479928",
        "free_parking": "NO",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "BLK 302/348 ANG MO KIO ST 31",
        "car_park_decks": "0",
        "_id": 5,
        "car_park_no": "AK31",
        "type_of_parking_system": "COUPON PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "x_coord": "1.3727497",
        "y_coord": "103.8502032",
        "free_parking": "NO",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLOCK 513 ANG MO KIO ST 53",
        "car_park_decks": "0",
        "_id": 6,
        "car_park_no": "AK52",
        "type_of_parking_system": "COUPON PARKING"
    },
    {
        "short_term_parking": "7AM-10.30PM",
        "car_park_type": "SURFACE CAR PARK",
        "x_coord": "1.3727031",
        "y_coord": "103.8456739",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "BLOCK 728 ANG MO KIO AVE 6",
        "car_park_decks": "0",
        "_id": 7,
        "car_park_no": "AK6",
        "type_of_parking_system": "COUPON PARKING"
    },
    {
        "short_term_parking": "NO",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.862846",
        "x_coord": "1.370195",
        "free_parking": "NO",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "BLK 5022 TO 5095 ANG MO KIO INDUSTRIAL PARK 2",
        "car_park_decks": "0",
        "_id": 8,
        "car_park_no": "AK83",
        "type_of_parking_system": "COUPON PARKING"
    },
    {
        "short_term_parking": "NO",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8476654",
        "x_coord": "1.3801427",
        "free_parking": "NO",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "ANG MO KIO AVENUE 9",
        "car_park_decks": "0",
        "_id": 9,
        "car_park_no": "AK9",
        "type_of_parking_system": "COUPON PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8402243",
        "x_coord": "1.3682723",
        "free_parking": "NO",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 227 ANG MO KIO ST 23",
        "car_park_decks": "6",
        "_id": 10,
        "car_park_no": "AM14",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8360907",
        "x_coord": "1.3701971",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 256A ANG MO KIO STREET 21",
        "car_park_decks": "2",
        "_id": 11,
        "car_park_no": "AM16",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "7AM-10.30PM",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8445072",
        "x_coord": "1.3651595",
        "free_parking": "NO",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "BLK 308C ANG MO KIO AVE 1",
        "car_park_decks": "3",
        "_id": 12,
        "car_park_no": "AM18",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8345779",
        "x_coord": "1.3688487",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 260 ANG MO KIO ST 21",
        "car_park_decks": "6",
        "_id": 13,
        "car_park_no": "AM19",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8459875",
        "x_coord": "1.3648216",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 309B ANG MO KIO ST 31",
        "car_park_decks": "12",
        "_id": 14,
        "car_park_no": "AM20",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8476215",
        "x_coord": "1.3646696",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 316B ANG MO KIO STREET 31",
        "car_park_decks": "12",
        "_id": 15,
        "car_park_no": "AM22",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8350565",
        "x_coord": "1.3704626",
        "free_parking": "NO",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 255A ANG MO KIO ST 21",
        "car_park_decks": "2",
        "_id": 16,
        "car_park_no": "AM32",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8573796",
        "x_coord": "1.3685769",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 455 ANG MO KIO ST 44",
        "car_park_decks": "7",
        "_id": 17,
        "car_park_no": "AM43",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8533049",
        "x_coord": "1.3725641",
        "free_parking": "NO",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 588 ANG MO KIO STREET 52",
        "car_park_decks": "5",
        "_id": 18,
        "car_park_no": "AM46",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.846489",
        "x_coord": "1.3696213",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 700 ANG MO KIO AVE 6",
        "car_park_decks": "12",
        "_id": 19,
        "car_park_no": "AM51",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8533031",
        "x_coord": "1.3715668",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 590 ANG MO KIO ST 51",
        "car_park_decks": "12",
        "_id": 20,
        "car_park_no": "AM64",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8533049",
        "x_coord": "1.3725641",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 596 ANG MO KIO STREEET 52",
        "car_park_decks": "12",
        "_id": 21,
        "car_park_no": "AM79",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8425185",
        "x_coord": "1.3706081",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 130A ANG MO KIO ST 12",
        "car_park_decks": "4",
        "_id": 22,
        "car_park_no": "AM80",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8427779",
        "x_coord": "1.3716033",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 132A ANG MO KIO ST 12",
        "car_park_decks": "4",
        "_id": 23,
        "car_park_no": "AM81",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8502584",
        "x_coord": "1.3645675",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 352A ANG MO KIO STREET 32",
        "car_park_decks": "12",
        "_id": 24,
        "car_park_no": "AM96",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "NO",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.7823530646428",
        "x_coord": "1.3042088856677838",
        "free_parking": "NO",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "3 AND 5 DOVER ROAD",
        "car_park_decks": "0",
        "_id": 25,
        "car_park_no": "AR1L",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.78363186649185",
        "x_coord": "1.3027209862950702",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 2A DOVER ROAD",
        "car_park_decks": "10",
        "_id": 26,
        "car_park_no": "AR1M",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "NO",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.7812842",
        "x_coord": "1.3054926",
        "free_parking": "NO",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "BLK 26 AND 27 DOVER CRESCENT",
        "car_park_decks": "0",
        "_id": 27,
        "car_park_no": "AR2L",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.7817026",
        "x_coord": "1.3047552",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 28 DOVER CRESCENT",
        "car_park_decks": "16",
        "_id": 28,
        "car_park_no": "AR2M",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.7843144",
        "x_coord": "1.3077691",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 19A DOVER CRESCENT",
        "car_park_decks": "12",
        "_id": 29,
        "car_park_no": "AR5M",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "NO",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.7854574",
        "x_coord": "1.3057307",
        "free_parking": "NO",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "12 TO 14 DOVER CLOSE EAST",
        "car_park_decks": "0",
        "_id": 30,
        "car_park_no": "AR7L",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.7851962",
        "x_coord": "1.3047981",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "2.15",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 12A DOVER CLOSE EAST",
        "car_park_decks": "7",
        "_id": 31,
        "car_park_no": "AR7M",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "7AM-10.30PM",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.7836157",
        "x_coord": "1.3074368",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "BLK 20/22/23 DOVER CRESCENT",
        "car_park_decks": "0",
        "_id": 32,
        "car_park_no": "AR9",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8045184",
        "x_coord": "1.2863397",
        "free_parking": "NO",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 120/120A/121-127 ALEXANDRA VILLAGE",
        "car_park_decks": "0",
        "_id": 33,
        "car_park_no": "AV1",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8029684",
        "x_coord": "1.2858387",
        "free_parking": "NO",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 1001/1010 BUKIT MERAH LANE 1/3",
        "car_park_decks": "0",
        "_id": 34,
        "car_park_no": "AV2",
        "type_of_parking_system": "COUPON PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8416078",
        "x_coord": "1.3664944",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 215 ANG MO KIO STREET 22",
        "car_park_decks": "0",
        "_id": 35,
        "car_park_no": "A1",
        "type_of_parking_system": "COUPON PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8430417",
        "x_coord": "1.3665712",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 201/202 ANG MO KIO STREET 22",
        "car_park_decks": "0",
        "_id": 36,
        "car_park_no": "A10",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8426804",
        "x_coord": "1.3776837",
        "free_parking": "NO",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 650 ANG MO KIO STREET 61",
        "car_park_decks": "0",
        "_id": 37,
        "car_park_no": "A100",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8377307",
        "x_coord": "1.3659533",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 223/226/226A-226D ANG MO KIO ST 22",
        "car_park_decks": "0",
        "_id": 38,
        "car_park_no": "A11",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8410177",
        "x_coord": "1.3671362",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 229/230 ANG MO KIO ST 22",
        "car_park_decks": "0",
        "_id": 39,
        "car_park_no": "A12",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8410177",
        "x_coord": "1.3671362",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 232/233 ANG MO KIO ST 22",
        "car_park_decks": "0",
        "_id": 40,
        "car_park_no": "A13",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8410177",
        "x_coord": "1.3671362",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 226E-226H ANG MO KIO ST 22",
        "car_park_decks": "0",
        "_id": 41,
        "car_park_no": "A15",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8410177",
        "x_coord": "1.3671362",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 206/207 ANG MO KIO STREET 22",
        "car_park_decks": "0",
        "_id": 42,
        "car_park_no": "A2",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8479928",
        "x_coord": "1.3659029",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 304/307/319 ANG MO KIO ST 31",
        "car_park_decks": "0",
        "_id": 43,
        "car_park_no": "A20",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8479928",
        "x_coord": "1.3659029",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 325/326/301 ANG MO KIO STREET 31",
        "car_park_decks": "0",
        "_id": 44,
        "car_park_no": "A21",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.8488895",
        "x_coord": "1.3672997",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "1.90",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 347A ANG MO KIO AVENUE 3",
        "car_park_decks": "10",
        "_id": 45,
        "car_park_no": "A23",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8502584",
        "x_coord": "1.3645675",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 338/340 ANG MO KIO ST 32",
        "car_park_decks": "0",
        "_id": 46,
        "car_park_no": "A24",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8486932",
        "x_coord": "1.3707675",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 330/337 ANG MO KIO AVE 8",
        "car_park_decks": "0",
        "_id": 47,
        "car_park_no": "A25",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8359818",
        "x_coord": "1.372687",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 113/114/118 ANG MO KIO AVE 4",
        "car_park_decks": "0",
        "_id": 48,
        "car_park_no": "A26",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8359091",
        "x_coord": "1.3709461",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "5.40",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 108/109/110 ANG MO KIO ST 11",
        "car_park_decks": "0",
        "_id": 49,
        "car_park_no": "A27",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8359091",
        "x_coord": "1.3709461",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 103/105/107 ANG MO KIO ST 11",
        "car_park_decks": "0",
        "_id": 50,
        "car_park_no": "A28",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8485709",
        "x_coord": "1.3673391",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 347 ANG MO KIO AVENUE 3",
        "car_park_decks": "0",
        "_id": 51,
        "car_park_no": "A29",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8419073",
        "x_coord": "1.3697104",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 129/134 ANG MO KIO STREET 12",
        "car_park_decks": "0",
        "_id": 52,
        "car_park_no": "A30",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "7AM-10.30PM",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8426847",
        "x_coord": "1.3711089",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "BLK 133 ANG MO KIO STREET 12",
        "car_park_decks": "0",
        "_id": 53,
        "car_park_no": "A30A",
        "type_of_parking_system": "COUPON PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8442962",
        "x_coord": "1.3718179",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 119/128 ANG MO KIO ST 12",
        "car_park_decks": "0",
        "_id": 54,
        "car_park_no": "A31",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "7AM-10.30PM",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8442962",
        "x_coord": "1.3718179",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "BLK 125/126 ANG MO KIO STREET 12",
        "car_park_decks": "0",
        "_id": 55,
        "car_park_no": "A31A",
        "type_of_parking_system": "COUPON PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.83434486839309",
        "x_coord": "1.369770442277334",
        "free_parking": "NO",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 253/254 ANG MO KIO STREET 21",
        "car_park_decks": "0",
        "_id": 56,
        "car_park_no": "A33",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85183054815357",
        "x_coord": "1.3693963933488993",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 422/425 ANG MO KIO ST 42",
        "car_park_decks": "0",
        "_id": 57,
        "car_park_no": "A34",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85405537737523",
        "x_coord": "1.3678893755290609",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 426/428/435 ANG MO KIO ST 43",
        "car_park_decks": "0",
        "_id": 58,
        "car_park_no": "A35",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85570872677425",
        "x_coord": "1.3675786950747633",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 436/443/445 ANG MO KIO ST 43",
        "car_park_decks": "0",
        "_id": 59,
        "car_park_no": "A36",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85504926777796",
        "x_coord": "1.367858746372645",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 446/449/453 ANG MO KIO ST 43",
        "car_park_decks": "0",
        "_id": 60,
        "car_park_no": "A37",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85420630245653",
        "x_coord": "1.362889224806824",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 407/410/421 ANG MO KIO AVE 10",
        "car_park_decks": "0",
        "_id": 61,
        "car_park_no": "A38",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8554242440154",
        "x_coord": "1.3614444065150668",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 401/405 ANG MO KIO AVE 10",
        "car_park_decks": "0",
        "_id": 62,
        "car_park_no": "A39",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84053372412797",
        "x_coord": "1.3655919399665382",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 217/220 ANG MO KIO AVENUE 1",
        "car_park_decks": "0",
        "_id": 63,
        "car_park_no": "A4",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.8575208691031",
        "x_coord": "1.3626801376412554",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "9.99",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 471/476 ANG MO KIO ST 44",
        "car_park_decks": "0",
        "_id": 64,
        "car_park_no": "A40",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85650572334792",
        "x_coord": "1.366184995730393",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 466/470 ANG MO KIO ST 44",
        "car_park_decks": "0",
        "_id": 65,
        "car_park_no": "A41",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85723794211702",
        "x_coord": "1.3678505661429456",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 461/465 ANG MO KIO ST 44",
        "car_park_decks": "0",
        "_id": 66,
        "car_park_no": "A42",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85884204211709",
        "x_coord": "1.3659557405424536",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 457/458/460 ANG MO KIO ST 44",
        "car_park_decks": "0",
        "_id": 67,
        "car_park_no": "A43",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85955243034644",
        "x_coord": "1.3681913073584369",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 459/456 ANG MO KIO ST 44",
        "car_park_decks": "0",
        "_id": 68,
        "car_park_no": "A44",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85600206910293",
        "x_coord": "1.3697584432673424",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 570/578 ANG MO KIO ST 51",
        "car_park_decks": "0",
        "_id": 69,
        "car_park_no": "A45",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85914525561002",
        "x_coord": "1.370385162818802",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 562/565/560 ANG MO KIO STREET 54",
        "car_park_decks": "0",
        "_id": 70,
        "car_park_no": "A47",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.94599745560998",
        "x_coord": "1.3730181428997936",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 571/73 ANG MO KIO ST 51",
        "car_park_decks": "0",
        "_id": 71,
        "car_park_no": "A48",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85678437095265",
        "x_coord": "1.3720128687744222",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 555/559 ANG MO KIO STREET 54",
        "car_park_decks": "0",
        "_id": 72,
        "car_park_no": "A49",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85764908259607",
        "x_coord": "1.372397271767638",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 548/552/556 ANG MO KIO STREET 54",
        "car_park_decks": "0",
        "_id": 73,
        "car_park_no": "A50",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.83522304026738",
        "x_coord": "1.3705824885700069",
        "free_parking": "NO",
        "gantry_height": "5.40",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 252/253A ANG MO KIO STREET 21",
        "car_park_decks": "0",
        "_id": 74,
        "car_park_no": "A51",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.847543769103",
        "x_coord": "1.3695231432938615",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 701/716 ANG MO KIO AVE 3/6",
        "car_park_decks": "0",
        "_id": 75,
        "car_park_no": "A52",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "NO",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84586736725343",
        "x_coord": "1.369656540192384",
        "free_parking": "NO",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "BLK 700B/ 700C ANG MO KIO AVE 3/6",
        "car_park_decks": "0",
        "_id": 76,
        "car_park_no": "A52L",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "MULTI-STOREY CAR PARK",
        "y_coord": "103.84771656910297",
        "x_coord": "1.369112740243878",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "1.80",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 712A ANG MO KIO AVE 3/6",
        "car_park_decks": "14",
        "_id": 77,
        "car_park_no": "A53",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84608398259613",
        "x_coord": "1.3728738914015828",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 727/728 ANG MO KIO AVE 6",
        "car_park_decks": "0",
        "_id": 78,
        "car_park_no": "A54",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84597788444567",
        "x_coord": "1.3741633942735698",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 729/730 ANG MO KIO AVE 6/8",
        "car_park_decks": "0",
        "_id": 79,
        "car_park_no": "A55",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84824278444566",
        "x_coord": "1.37240261720989",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 725/730 ANG MO KIO AVE 8",
        "car_park_decks": "0",
        "_id": 80,
        "car_park_no": "A56",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84720214026741",
        "x_coord": "1.3727051429351198",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 720/723 ANG MO KIO AVE 8",
        "car_park_decks": "0",
        "_id": 81,
        "car_park_no": "A57",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84747806910303",
        "x_coord": "1.372522697509803",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 721/722 ANG MO KIO AVE 8",
        "car_park_decks": "0",
        "_id": 82,
        "car_park_no": "A58",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85826569793865",
        "x_coord": "1.37444438823809",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "3.80",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 547/551 ANG MO KIO ST 54",
        "car_park_decks": "0",
        "_id": 83,
        "car_park_no": "A59",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85484945561",
        "x_coord": "1.3752212228793534",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 540/546 ANG MO KIO ST 54",
        "car_park_decks": "0",
        "_id": 84,
        "car_park_no": "A60",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85118025084337",
        "x_coord": "1.3736504036920265",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "9.99",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 520/534/529 ANG MO KIO AVE 5/10",
        "car_park_decks": "0",
        "_id": 85,
        "car_park_no": "A61",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84907529978834",
        "x_coord": "1.3741506230340361",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "5.40",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 501/513/508 ANG MO KIO ST 52/53",
        "car_park_decks": "0",
        "_id": 86,
        "car_park_no": "A63",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85415645560998",
        "x_coord": "1.3708549370145982",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "5.40",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 584/586 ANG MO KIO ST 51",
        "car_park_decks": "0",
        "_id": 87,
        "car_park_no": "A64",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.85917159793857",
        "x_coord": "1.3714244627342171",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 558/560 ANG MO KIO STREET 54",
        "car_park_decks": "0",
        "_id": 88,
        "car_park_no": "A65",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.83533489204603",
        "x_coord": "1.3804550674382126",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "5.40",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 601/604/603 ANG MO KIO AVE 5",
        "car_park_decks": "0",
        "_id": 89,
        "car_park_no": "A66",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.83663240430603",
        "x_coord": "1.3802484975791842",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 605/612 ANG MO KIO AVE 4/5",
        "car_park_decks": "0",
        "_id": 90,
        "car_park_no": "A67",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.83999798074643",
        "x_coord": "1.3812678047407017",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 620/624/626 ANG MO KIO ST 61",
        "car_park_decks": "0",
        "_id": 91,
        "car_park_no": "A68",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84083988629524",
        "x_coord": "1.382802333243623",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "5.40",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 623/625/627 ANG MO KIO ST 61",
        "car_park_decks": "0",
        "_id": 92,
        "car_park_no": "A69",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84126753014057",
        "x_coord": "1.3680441179317666",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 212/213 ANG MO KIO STREET 23",
        "car_park_decks": "0",
        "_id": 93,
        "car_park_no": "A7",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84009454026737",
        "x_coord": "1.3813428847676725",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "9.99",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 629/626 ANG MO KIO AVE 4",
        "car_park_decks": "0",
        "_id": 94,
        "car_park_no": "A70",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84090766725338",
        "x_coord": "1.3812319905304729",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "5.40",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 628/632 ANG MO KIO ST 61",
        "car_park_decks": "0",
        "_id": 95,
        "car_park_no": "A71",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84196769686876",
        "x_coord": "1.382373632133777",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "5.40",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 633/640 ANG MO KIO ST 61",
        "car_park_decks": "0",
        "_id": 96,
        "car_park_no": "A72",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "NO",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.91116869978833",
        "x_coord": "1.3995868885990468",
        "free_parking": "NO",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "NO",
        "address": "PUNGGOL CENTRAL",
        "car_park_decks": "0",
        "_id": 1235,
        "car_park_no": "P35L",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84189168216818",
        "x_coord": "1.3793935044750374",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 641/645 ANG MO KIO ST 61",
        "car_park_decks": "0",
        "_id": 97,
        "car_park_no": "A73",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.84334227965519",
        "x_coord": "1.3797588173691706",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "0.00",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 646/649 ANG MO KIO ST 61",
        "car_park_decks": "0",
        "_id": 98,
        "car_park_no": "A74",
        "type_of_parking_system": "ELECTRONIC PARKING"
    },
    {
        "short_term_parking": "WHOLE DAY",
        "car_park_type": "SURFACE CAR PARK",
        "y_coord": "103.83803653177746",
        "x_coord": "1.3761913179088627",
        "free_parking": "SUN & PH FR 7AM-10.30PM",
        "gantry_height": "4.50",
        "car_park_basement": "N",
        "night_parking": "YES",
        "address": "BLK 177/182 ANG MO KIO AVE 4",
        "car_park_decks": "0",
        "_id": 99,
        "car_park_no": "A75",
        "type_of_parking_system": "ELECTRONIC PARKING"
    }
]